return {
            "EdenEast/nightfox.nvim",
            "ellisonleao/gruvbox.nvim" ,
            "savq/melange",
            'Mofiqul/dracula.nvim',
            'NTBBloodbath/doom-one.nvim',
            'Shatur/neovim-ayu',
            'bluz71/vim-moonfly-colors',
            'bluz71/vim-nightfly-guicolors',
            { 'folke/tokyonight.nvim', disable = false , bufread = false },
            'patstockwell/vim-monokai-tasty',
            'rmehri01/onenord.nvim',
            { 'lalitmee/cobalt2.nvim', requires = 'tjdevries/colorbuddy.nvim' },
            { 'luisiacc/gruvbox-baby', branch = 'main'},
            { "catppuccin/nvim", as = "catppuccin" },
            'loctvl842/monokai-pro.nvim',
            "navarasu/onedark.nvim",
            "NLKNguyen/papercolor-theme",
            'arcticicestudio/nord-vim',
            { "bluz71/vim-nightfly-colors", as = "nightfly" },
}
