require("zack.globals.options")
require("zack.globals.keymaps")
require("zack.plugins")

require("zack.plugins")
require("zack.plugin")

-- vim.cmd("colorscheme ayu-mirage")
require("zack.plugin.lualine")
require("zack.plugin.telescope")
require("zack.plugin.nvim-cmp")
require("zack.plugin.lsp")
require("zack.plugin.which-key")
require("zack.plugin.color")
require("zack.plugin.nvim-tree")
